name: Build and deploy

on:
  push:
    branches:
      - dev
      - prod
  workflow_dispatch:

jobs:
  build_image:
    runs-on: stackit-ubuntu-22
    uses: ./.forgejo/workflows/build-image.yaml
    secrets: inherit

  deploy:
    needs: build_image
    runs-on: stackit-ubuntu-22
    uses: ./.forgejo/workflows/deploy.yaml
    with:
      stage: ${{ github.ref_name }}
      image_repository: ${{ needs.build_image.outputs.image_repository }}
      image_digest: ${{ needs.build_image.outputs.image_digest }}
    secrets: inherit
