apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: haproxy
  tls:
    - hosts:
        - {{ required "ingress.hostname is required" .Values.ingress.hostname | quote }}
      secretName: {{ default (printf "%s-tls" (include "app.fullname" .)) .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ required "ingress.hostname is required" .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
